### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by SkyLeite** [KazeSenoue/MemePatcher#4]
### General functionality
- [ ] Implement logging
- [ ] PSO2 settings menu

#### English patch
- [x] Download from source (55ed165) (to be re-done)
- [x] Proper UI implementation (change HttpClient to WebClient for progress bar)
- [ ] Large files

#### Updating
- [x] Check files
- [x] Move file check stuff to `Cache.cs`
- [x] Update cache file
- [x] Download missing / corrupt files (Implemented initially, gotta work on user clarity and code readability)

#### Bugs
- [x] `ffbff2ac5b7a7948961212cefd4d402c` always returns as missing for some reason

#### Other
- [x] Rewrite settings system
- [ ] Some sort of global progress bar / label control (calling Main every time is awful)
